spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    suffix: .html
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:./test
    schema: classpath:db/db.sql

  h2:
    console:
      enabled: true
      path: /h2-console

